services:
  nginx:
    image: nginx:alpine-slim
    volumes:
      - ./.docker-compose/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - '8083:4000'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      TZ: America/Sao_Paulo
    volumes:
      - .docker-compose/nginx/conf.d/dash.tasks.com.br.conf:/etc/nginx/conf.d/default.conf